# DigitalOcean App Platform Configuration
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: greeco-laravel

services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: lamtruong1006/greeco-laravel
      branch: master
      deploy_on_push: true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs # $5/month - có thể nâng cấp sau
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: APP_NAME
        value: "GREECO"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "${APP_URL}"
        scope: RUN_AND_BUILD_TIME
      - key: APP_KEY
        value: "${APP_KEY}"
        type: SECRET
      - key: LOG_CHANNEL
        value: "stderr"
      - key: LOG_LEVEL
        value: "error"
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "${db.HOSTNAME}"
      - key: DB_PORT
        value: "${db.PORT}"
      - key: DB_DATABASE
        value: "${db.DATABASE}"
      - key: DB_USERNAME
        value: "${db.USERNAME}"
      - key: DB_PASSWORD
        value: "${db.PASSWORD}"
        type: SECRET
      - key: CACHE_DRIVER
        value: "file"
      - key: SESSION_DRIVER
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: FILESYSTEM_DISK
        value: "public"

databases:
  - name: db
    engine: MYSQL
    num_nodes: 1
    size: db-s-1vcpu-1gb # $15/month - có thể dùng managed database bên ngoài
    version: "8"
