# DigitalOcean App Platform Configuration
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: greeco-laravel

services:
  - name: web
    github:
      repo: lamtruong1006/greeco-laravel
      branch: master
      deploy_on_push: true
    environment_slug: php
    build_command: |
      npm ci &&
      npm run build &&
      composer install --no-dev --optimize-autoloader &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan storage:link
    run_command: heroku-php-apache2 public/
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: APP_NAME
        value: "GREECO"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "${APP_URL}"
        scope: RUN_AND_BUILD_TIME
      - key: APP_KEY
        value: "${APP_KEY}"
        type: SECRET
      - key: LOG_CHANNEL
        value: "stderr"
      - key: LOG_LEVEL
        value: "error"
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "db-mysql-sgp1-lienquan-do-user-26785433-0.g.db.ondigitalocean.com"
      - key: DB_PORT
        value: "25060"
      - key: DB_DATABASE
        value: "greeco"
      - key: DB_USERNAME
        value: "doadmin"
      - key: DB_PASSWORD
        value: "${DB_PASSWORD}"
        type: SECRET
      - key: MYSQL_ATTR_SSL_CA
        value: "/etc/ssl/certs/ca-certificates.crt"
      - key: CACHE_DRIVER
        value: "file"
      - key: SESSION_DRIVER
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: FILESYSTEM_DISK
        value: "public"
